### ISSUE TITLE
pet_cat doesn't work with the cat data frame

### ISSUE THREAD

**Issue by sowla** [RMHogervorst/satrdayamsterdam_for_tha_loop#3]
The pet_cat function works as a stand alone example (like below), but in the cat data frame, there are cat emojis in front of the names (eg. `paste(emo::ji("cat"), "Margaret")`). So none of the cats are getting petted :(

I don't know if you'd prefer to keep the cat emoji, keep the code simple or if you have an alternative solution :)

```{r}
pet_cat <- 
    function(name){
    if(name %in% c("Margaret", "Tibbles")){
        "pet"
    }else{
        "don't pet, stay away!"
    }
}
pet_cat("Donald")
pet_cat("Tibbles")
```

**Comment by RMHogervorst** [comment]
Thanks!

**Comment by RMHogervorst** [comment]
For similicity sake we might better not use the emoji.... But I like them so much! @rendrikson What do you think?

**Comment by rendrikson** [comment]
Since for me it is rather not too serious post (not that we shouldn't take functional programming seriously), I would go with emojis. Nevertheless, I totally agree that all this emoji thing makes it much harder to follow, so I don't mind not using them ... but I will not forget them neither

**Comment by RMHogervorst** [comment]
Fair enough. Thanks for the input both!
